-- Supabase Schema for AI News Search Assistant
-- Enable pgvector extension
create extension if not exists vector;

-- Create articles table
create table if not exists articles (
    id bigint primary key generated always as identity,
    url text unique not null,
    title text,
    content text,
    category text,
    source text,
    created_at timestamp with time zone,
    
    -- AI fields
    embedding vector(1536),
    is_enriched boolean default false,
    sentiment text,      -- 'pozitiv', 'neytral', 'riskli'
    summary_az text      -- Short Azerbaijani summary generated by GPT-4o
);

-- Create an index for faster vector similarity search
create index on articles using ivfflat (embedding vector_cosine_ops)
with (lists = 100);

-- RPC Function for Hybrid Search (Date Filter + Vector Similarity)
create or replace function search_news(
    query_embedding vector(1536),
    date_from timestamp with time zone default null,
    date_to timestamp with time zone default null,
    match_count int default 15
)
returns table (
    id bigint,
    title text,
    content text,
    url text,
    category text,
    source text,
    created_at timestamp with time zone,
    is_enriched boolean,
    sentiment text,
    summary_az text,
    similarity float
)
language plpgsql
as $$
begin
    return query
    select
        a.id,
        a.title,
        a.content,
        a.url,
        a.category,
        a.source,
        a.created_at,
        a.is_enriched,
        a.sentiment,
        a.summary_az,
        1 - (a.embedding <=> query_embedding) as similarity
    from articles a
    where
        -- Apply date filters if provided
        (date_from is null or a.created_at >= date_from)
        and
        (date_to is null or a.created_at <= (date_to + interval '1 day' - interval '1 second'))
    order by
        a.embedding <=> query_embedding
    limit match_count;
end;
$$;

-- Digests table for web dashboard display
create table if not exists digests (
    id bigint primary key generated always as identity,
    date date unique not null,
    article_count int default 0,
    articles jsonb,
    created_at timestamp with time zone default now()
);
